spring:
  application:
    name: spring-admin
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          scrape: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
